
spring:
  data:
    mongodb:
      authentication-database: admin
      user: ${mongodb_user}
      password: ${mongodb_password}
      host: localhost
      port: 27017
      database: customerServiceDB

  application:
    name: CustomerService
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
          auto-add-partitions: true
      bindings:
        customerOrderEvent-in-0:
          destination: customerOrderEvent
          content-type: application/*+avro
          group: orderServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000

  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



