spring:
  data:
    mongodb:
      authentication-database: admin
      user: ${mongodb_user}
      password: ${mongodb_password}
      host: localhost
      port: 27017
      database: productServiceDB
  cloud:
    stream:
      kafka:
        bindings:
          orderEvent-in-0:
            consumer:
              ackMode: MANUAL
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
          auto-add-partitions: true
      bindings:
        orderEvent-in-0:
          destination: orderEvent
          content-type: application/*+avro
          group: orderServiceGroup
          consumer:
            instanceCount: 2
            instanceIndex: 2
            max-attempts: 4
            back-off-initial-interval: 10000

  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

logging:
  file:
    path: /Users/m80007278/Documents/loggings
