/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.possible.commonslib.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class VendorEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6955096970841920322L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"VendorEvent\",\"namespace\":\"com.possible.commonslib.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"phone\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"companyName\",\"type\":\"string\"},{\"name\":\"companyLogo\",\"type\":\"string\"},{\"name\":\"desc\",\"type\":\"string\"},{\"name\":\"gender\",\"type\":\"string\"},{\"name\":\"companyAddress\",\"type\":{\"type\":\"record\",\"name\":\"Address\",\"fields\":[{\"name\":\"street\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"zip\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"latitude\",\"type\":[\"int\",\"null\"]},{\"name\":\"longitude\",\"type\":[\"int\",\"null\"]}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<VendorEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<VendorEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<VendorEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<VendorEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<VendorEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this VendorEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a VendorEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a VendorEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static VendorEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private java.lang.CharSequence firstName;
  private java.lang.CharSequence lastName;
  private java.lang.CharSequence phone;
  private java.lang.CharSequence email;
  private java.lang.CharSequence companyName;
  private java.lang.CharSequence companyLogo;
  private java.lang.CharSequence desc;
  private java.lang.CharSequence gender;
  private com.possible.commonslib.avro.Address companyAddress;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public VendorEvent() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param firstName The new value for firstName
   * @param lastName The new value for lastName
   * @param phone The new value for phone
   * @param email The new value for email
   * @param companyName The new value for companyName
   * @param companyLogo The new value for companyLogo
   * @param desc The new value for desc
   * @param gender The new value for gender
   * @param companyAddress The new value for companyAddress
   */
  public VendorEvent(java.lang.CharSequence id, java.lang.CharSequence firstName, java.lang.CharSequence lastName, java.lang.CharSequence phone, java.lang.CharSequence email, java.lang.CharSequence companyName, java.lang.CharSequence companyLogo, java.lang.CharSequence desc, java.lang.CharSequence gender, com.possible.commonslib.avro.Address companyAddress) {
    this.id = id;
    this.firstName = firstName;
    this.lastName = lastName;
    this.phone = phone;
    this.email = email;
    this.companyName = companyName;
    this.companyLogo = companyLogo;
    this.desc = desc;
    this.gender = gender;
    this.companyAddress = companyAddress;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return firstName;
    case 2: return lastName;
    case 3: return phone;
    case 4: return email;
    case 5: return companyName;
    case 6: return companyLogo;
    case 7: return desc;
    case 8: return gender;
    case 9: return companyAddress;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: firstName = (java.lang.CharSequence)value$; break;
    case 2: lastName = (java.lang.CharSequence)value$; break;
    case 3: phone = (java.lang.CharSequence)value$; break;
    case 4: email = (java.lang.CharSequence)value$; break;
    case 5: companyName = (java.lang.CharSequence)value$; break;
    case 6: companyLogo = (java.lang.CharSequence)value$; break;
    case 7: desc = (java.lang.CharSequence)value$; break;
    case 8: gender = (java.lang.CharSequence)value$; break;
    case 9: companyAddress = (com.possible.commonslib.avro.Address)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return The value of the 'firstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }


  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }


  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'phone' field.
   * @return The value of the 'phone' field.
   */
  public java.lang.CharSequence getPhone() {
    return phone;
  }


  /**
   * Sets the value of the 'phone' field.
   * @param value the value to set.
   */
  public void setPhone(java.lang.CharSequence value) {
    this.phone = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'companyName' field.
   * @return The value of the 'companyName' field.
   */
  public java.lang.CharSequence getCompanyName() {
    return companyName;
  }


  /**
   * Sets the value of the 'companyName' field.
   * @param value the value to set.
   */
  public void setCompanyName(java.lang.CharSequence value) {
    this.companyName = value;
  }

  /**
   * Gets the value of the 'companyLogo' field.
   * @return The value of the 'companyLogo' field.
   */
  public java.lang.CharSequence getCompanyLogo() {
    return companyLogo;
  }


  /**
   * Sets the value of the 'companyLogo' field.
   * @param value the value to set.
   */
  public void setCompanyLogo(java.lang.CharSequence value) {
    this.companyLogo = value;
  }

  /**
   * Gets the value of the 'desc' field.
   * @return The value of the 'desc' field.
   */
  public java.lang.CharSequence getDesc() {
    return desc;
  }


  /**
   * Sets the value of the 'desc' field.
   * @param value the value to set.
   */
  public void setDesc(java.lang.CharSequence value) {
    this.desc = value;
  }

  /**
   * Gets the value of the 'gender' field.
   * @return The value of the 'gender' field.
   */
  public java.lang.CharSequence getGender() {
    return gender;
  }


  /**
   * Sets the value of the 'gender' field.
   * @param value the value to set.
   */
  public void setGender(java.lang.CharSequence value) {
    this.gender = value;
  }

  /**
   * Gets the value of the 'companyAddress' field.
   * @return The value of the 'companyAddress' field.
   */
  public com.possible.commonslib.avro.Address getCompanyAddress() {
    return companyAddress;
  }


  /**
   * Sets the value of the 'companyAddress' field.
   * @param value the value to set.
   */
  public void setCompanyAddress(com.possible.commonslib.avro.Address value) {
    this.companyAddress = value;
  }

  /**
   * Creates a new VendorEvent RecordBuilder.
   * @return A new VendorEvent RecordBuilder
   */
  public static com.possible.commonslib.avro.VendorEvent.Builder newBuilder() {
    return new com.possible.commonslib.avro.VendorEvent.Builder();
  }

  /**
   * Creates a new VendorEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new VendorEvent RecordBuilder
   */
  public static com.possible.commonslib.avro.VendorEvent.Builder newBuilder(com.possible.commonslib.avro.VendorEvent.Builder other) {
    if (other == null) {
      return new com.possible.commonslib.avro.VendorEvent.Builder();
    } else {
      return new com.possible.commonslib.avro.VendorEvent.Builder(other);
    }
  }

  /**
   * Creates a new VendorEvent RecordBuilder by copying an existing VendorEvent instance.
   * @param other The existing instance to copy.
   * @return A new VendorEvent RecordBuilder
   */
  public static com.possible.commonslib.avro.VendorEvent.Builder newBuilder(com.possible.commonslib.avro.VendorEvent other) {
    if (other == null) {
      return new com.possible.commonslib.avro.VendorEvent.Builder();
    } else {
      return new com.possible.commonslib.avro.VendorEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for VendorEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<VendorEvent>
    implements org.apache.avro.data.RecordBuilder<VendorEvent> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence firstName;
    private java.lang.CharSequence lastName;
    private java.lang.CharSequence phone;
    private java.lang.CharSequence email;
    private java.lang.CharSequence companyName;
    private java.lang.CharSequence companyLogo;
    private java.lang.CharSequence desc;
    private java.lang.CharSequence gender;
    private com.possible.commonslib.avro.Address companyAddress;
    private com.possible.commonslib.avro.Address.Builder companyAddressBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.possible.commonslib.avro.VendorEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.firstName)) {
        this.firstName = data().deepCopy(fields()[1].schema(), other.firstName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.phone)) {
        this.phone = data().deepCopy(fields()[3].schema(), other.phone);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.email)) {
        this.email = data().deepCopy(fields()[4].schema(), other.email);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.companyName)) {
        this.companyName = data().deepCopy(fields()[5].schema(), other.companyName);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.companyLogo)) {
        this.companyLogo = data().deepCopy(fields()[6].schema(), other.companyLogo);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.desc)) {
        this.desc = data().deepCopy(fields()[7].schema(), other.desc);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.gender)) {
        this.gender = data().deepCopy(fields()[8].schema(), other.gender);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.companyAddress)) {
        this.companyAddress = data().deepCopy(fields()[9].schema(), other.companyAddress);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (other.hasCompanyAddressBuilder()) {
        this.companyAddressBuilder = com.possible.commonslib.avro.Address.newBuilder(other.getCompanyAddressBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing VendorEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.possible.commonslib.avro.VendorEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.firstName)) {
        this.firstName = data().deepCopy(fields()[1].schema(), other.firstName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.phone)) {
        this.phone = data().deepCopy(fields()[3].schema(), other.phone);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.email)) {
        this.email = data().deepCopy(fields()[4].schema(), other.email);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.companyName)) {
        this.companyName = data().deepCopy(fields()[5].schema(), other.companyName);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.companyLogo)) {
        this.companyLogo = data().deepCopy(fields()[6].schema(), other.companyLogo);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.desc)) {
        this.desc = data().deepCopy(fields()[7].schema(), other.desc);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.gender)) {
        this.gender = data().deepCopy(fields()[8].schema(), other.gender);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.companyAddress)) {
        this.companyAddress = data().deepCopy(fields()[9].schema(), other.companyAddress);
        fieldSetFlags()[9] = true;
      }
      this.companyAddressBuilder = null;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }


    /**
      * Sets the value of the 'firstName' field.
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.firstName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'firstName' field.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }


    /**
      * Sets the value of the 'lastName' field.
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.lastName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lastName' field.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'phone' field.
      * @return The value.
      */
    public java.lang.CharSequence getPhone() {
      return phone;
    }


    /**
      * Sets the value of the 'phone' field.
      * @param value The value of 'phone'.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder setPhone(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.phone = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'phone' field has been set.
      * @return True if the 'phone' field has been set, false otherwise.
      */
    public boolean hasPhone() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'phone' field.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder clearPhone() {
      phone = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.email = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder clearEmail() {
      email = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyName' field.
      * @return The value.
      */
    public java.lang.CharSequence getCompanyName() {
      return companyName;
    }


    /**
      * Sets the value of the 'companyName' field.
      * @param value The value of 'companyName'.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder setCompanyName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.companyName = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'companyName' field has been set.
      * @return True if the 'companyName' field has been set, false otherwise.
      */
    public boolean hasCompanyName() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'companyName' field.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder clearCompanyName() {
      companyName = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyLogo' field.
      * @return The value.
      */
    public java.lang.CharSequence getCompanyLogo() {
      return companyLogo;
    }


    /**
      * Sets the value of the 'companyLogo' field.
      * @param value The value of 'companyLogo'.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder setCompanyLogo(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.companyLogo = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'companyLogo' field has been set.
      * @return True if the 'companyLogo' field has been set, false otherwise.
      */
    public boolean hasCompanyLogo() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'companyLogo' field.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder clearCompanyLogo() {
      companyLogo = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'desc' field.
      * @return The value.
      */
    public java.lang.CharSequence getDesc() {
      return desc;
    }


    /**
      * Sets the value of the 'desc' field.
      * @param value The value of 'desc'.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder setDesc(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.desc = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'desc' field has been set.
      * @return True if the 'desc' field has been set, false otherwise.
      */
    public boolean hasDesc() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'desc' field.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder clearDesc() {
      desc = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'gender' field.
      * @return The value.
      */
    public java.lang.CharSequence getGender() {
      return gender;
    }


    /**
      * Sets the value of the 'gender' field.
      * @param value The value of 'gender'.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder setGender(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.gender = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'gender' field has been set.
      * @return True if the 'gender' field has been set, false otherwise.
      */
    public boolean hasGender() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'gender' field.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder clearGender() {
      gender = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyAddress' field.
      * @return The value.
      */
    public com.possible.commonslib.avro.Address getCompanyAddress() {
      return companyAddress;
    }


    /**
      * Sets the value of the 'companyAddress' field.
      * @param value The value of 'companyAddress'.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder setCompanyAddress(com.possible.commonslib.avro.Address value) {
      validate(fields()[9], value);
      this.companyAddressBuilder = null;
      this.companyAddress = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'companyAddress' field has been set.
      * @return True if the 'companyAddress' field has been set, false otherwise.
      */
    public boolean hasCompanyAddress() {
      return fieldSetFlags()[9];
    }

    /**
     * Gets the Builder instance for the 'companyAddress' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.possible.commonslib.avro.Address.Builder getCompanyAddressBuilder() {
      if (companyAddressBuilder == null) {
        if (hasCompanyAddress()) {
          setCompanyAddressBuilder(com.possible.commonslib.avro.Address.newBuilder(companyAddress));
        } else {
          setCompanyAddressBuilder(com.possible.commonslib.avro.Address.newBuilder());
        }
      }
      return companyAddressBuilder;
    }

    /**
     * Sets the Builder instance for the 'companyAddress' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.possible.commonslib.avro.VendorEvent.Builder setCompanyAddressBuilder(com.possible.commonslib.avro.Address.Builder value) {
      clearCompanyAddress();
      companyAddressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'companyAddress' field has an active Builder instance
     * @return True if the 'companyAddress' field has an active Builder instance
     */
    public boolean hasCompanyAddressBuilder() {
      return companyAddressBuilder != null;
    }

    /**
      * Clears the value of the 'companyAddress' field.
      * @return This builder.
      */
    public com.possible.commonslib.avro.VendorEvent.Builder clearCompanyAddress() {
      companyAddress = null;
      companyAddressBuilder = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public VendorEvent build() {
      try {
        VendorEvent record = new VendorEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.firstName = fieldSetFlags()[1] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.lastName = fieldSetFlags()[2] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.phone = fieldSetFlags()[3] ? this.phone : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.email = fieldSetFlags()[4] ? this.email : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.companyName = fieldSetFlags()[5] ? this.companyName : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.companyLogo = fieldSetFlags()[6] ? this.companyLogo : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.desc = fieldSetFlags()[7] ? this.desc : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.gender = fieldSetFlags()[8] ? this.gender : (java.lang.CharSequence) defaultValue(fields()[8]);
        if (companyAddressBuilder != null) {
          try {
            record.companyAddress = this.companyAddressBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("companyAddress"));
            throw e;
          }
        } else {
          record.companyAddress = fieldSetFlags()[9] ? this.companyAddress : (com.possible.commonslib.avro.Address) defaultValue(fields()[9]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<VendorEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<VendorEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<VendorEvent>
    READER$ = (org.apache.avro.io.DatumReader<VendorEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.firstName);

    out.writeString(this.lastName);

    out.writeString(this.phone);

    out.writeString(this.email);

    out.writeString(this.companyName);

    out.writeString(this.companyLogo);

    out.writeString(this.desc);

    out.writeString(this.gender);

    this.companyAddress.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);

      this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);

      this.phone = in.readString(this.phone instanceof Utf8 ? (Utf8)this.phone : null);

      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

      this.companyName = in.readString(this.companyName instanceof Utf8 ? (Utf8)this.companyName : null);

      this.companyLogo = in.readString(this.companyLogo instanceof Utf8 ? (Utf8)this.companyLogo : null);

      this.desc = in.readString(this.desc instanceof Utf8 ? (Utf8)this.desc : null);

      this.gender = in.readString(this.gender instanceof Utf8 ? (Utf8)this.gender : null);

      if (this.companyAddress == null) {
        this.companyAddress = new com.possible.commonslib.avro.Address();
      }
      this.companyAddress.customDecode(in);

    } else {
      for (int i = 0; i < 10; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);
          break;

        case 2:
          this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);
          break;

        case 3:
          this.phone = in.readString(this.phone instanceof Utf8 ? (Utf8)this.phone : null);
          break;

        case 4:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        case 5:
          this.companyName = in.readString(this.companyName instanceof Utf8 ? (Utf8)this.companyName : null);
          break;

        case 6:
          this.companyLogo = in.readString(this.companyLogo instanceof Utf8 ? (Utf8)this.companyLogo : null);
          break;

        case 7:
          this.desc = in.readString(this.desc instanceof Utf8 ? (Utf8)this.desc : null);
          break;

        case 8:
          this.gender = in.readString(this.gender instanceof Utf8 ? (Utf8)this.gender : null);
          break;

        case 9:
          if (this.companyAddress == null) {
            this.companyAddress = new com.possible.commonslib.avro.Address();
          }
          this.companyAddress.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










